// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0pELWzFLIf1j38Ghrv9o0OoXZH1gWZ6E',
    appId: '1:827267712942:android:6e8383c977196800212a3f',
    messagingSenderId: '827267712942',
    projectId: 'jaldharan',
    databaseURL: 'https://jaldharan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jaldharan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1c7LT8OFoRuV5R-S2G0z62zxTi7sRUaU',
    appId: '1:827267712942:ios:021c476f31e077ff212a3f',
    messagingSenderId: '827267712942',
    projectId: 'jaldharan',
    databaseURL: 'https://jaldharan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jaldharan.firebasestorage.app',
    androidClientId: '827267712942-q2m6qredqo1rjcc44f3gghp098jrdi0s.apps.googleusercontent.com',
    iosClientId: '827267712942-4c8ttv07m5u74kt8tmc52tv823abc0me.apps.googleusercontent.com',
    iosBundleId: 'com.litsquad.projects.jalDharan',
  );
}
